name: Prestige
main: rankup\RankUp
version: 1.0.0
author: Falkirks
api: [3.0.0]
load: POSTWORLD
softdepend: ["EconomyAPI", "PocketMoney", "PurePerms"]
permissions:
 prestige:
  default: true
  children:
    prestige.rankup:
      default: true
      description: Allow ranking up
    prestige.admin:
      default: op
      description: Manage RankUp and view statistics
    rankup.groups:
      default: false
      description: Do NOT set this. It is used for group managment.
